### your site title here

title: Your Name
description: subtitle | affiliations | motto

baseurl: # name of the repository
email: jitin.s.nair@gmail.com


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4

# Social media links in footer
facebook:
twitter: jitinnair1
linkedin: jitinnair1
github: jitinnair1
researchgate:
orcid: 0000-0001-7004-9377

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
